# GET all actors
GET http://localhost:3001/api/actor

# GET actors count by (count)
GET http://localhost:3001/api/actor/count

# GET actors Order by (sort)
GET http://localhost:3001/api/actor/sort/first_name

# GET actors by search, column and query by your choosing (search)
GET http://localhost:3001/api/actor/search/first_name/tim

# GET actors by first name, last letter y
GET http://localhost:3001/api/actor/findActorByFirstNameLastLetterY

# GET actors by last name, last letter e
GET http://localhost:3001/api/actor/findActorByLastNameLastLetterE

# GET single actor (id)
GET http://localhost:3001/api/actor/4